In [2]:
import tensorflow as tf

In [3]:
hello = tf.constant('Hello, TensorFlow!')
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [4]:
# 그래프 생성

a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a, b)
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [5]:
# 그래프의 실행은 Session안에서 이루어짐 (run메서드 이용)
# 모델 구성과 실행 분리

sess = tf.Session()

print(sess.run(hello))
print(sess.run([a,b,c]))

sess.close()

b'Hello, TensorFlow!'
[10, 32, 42]


In [6]:
# placeholder : 그래프에 사용할 입력값 나중에 받기위해 사용하는 매개변수
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [7]:
x_data = [[1,2,3], [4,5,6]]

In [8]:
# 정규분포의 무작위 값으로 초기화
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([2, 1]))

In [9]:
W = tf.Variable([[0.1, 0.1],[0.2, 0.2], [0.3, 0.3]])

In [10]:
expr = tf.matmul(X, W) + b

In [11]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
print(sess.run(expr, feed_dict={X: x_data}))

sess.close()

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[0.1 0.1]
 [0.2 0.2]
 [0.3 0.3]]
=== b ===
[[-0.03363047]
 [-0.6697929 ]]
=== expr ===
[[1.3663696 1.3663696]
 [2.5302072 2.5302072]]


In [12]:
x_data = [1,2,3]
y_data = [1,2,3]

In [13]:
# 균등분포의 무작위 값으로 초기화
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))

In [14]:
X = tf.placeholder(tf.float32, name="X")
Y = tf.placeholder(tf.float32, name="Y")

In [15]:
# X와 Y의 상관관계 분석 수식
# W는 가중치, b는 편향
hypothesis = W * X + b

In [16]:
# 손실함수
# 손실값: 실제값과 모델 예측값 차이 나타내는 값
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [17]:
# 최적화 함수 이용해 손실값 최소화
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train_op = optimizer.minimize(cost)

In [18]:
# 그래프 실행하여 학습
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(100) :
        _, cost_val = sess.run([train_op, cost], feed_dict={X: x_data, Y: y_data})
    
    
        print(step, cost_val, sess.run(W), sess.run(b))
      
print("X: 5, Y:", sess.run(hypothesis, feed_dict={X: 5}))
print("X: 2.5, Y:", sess.run(hypothesis, feed_dict={X: 2.5}))

0 0.7733863 [1.1329174] [-0.201266]
1 0.015947146 [1.0893676] [-0.21417977]
2 0.006580695 [1.0916297] [-0.20709087]
3 0.006165274 [1.088945] [-0.2023246]
4 0.0058711986 [1.0868595] [-0.19743769]
5 0.005592288 [1.0847657] [-0.19269393]
6 0.0053266524 [1.0827286] [-0.18806142]
7 0.0050736307 [1.0807399] [-0.18354057]
8 0.004832627 [1.0787989] [-0.17912838]
9 0.0046030823 [1.0769047] [-0.17482226]
10 0.004384421 [1.075056] [-0.17061965]
11 0.0041761585 [1.0732516] [-0.16651809]
12 0.0039777854 [1.0714908] [-0.1625151]
13 0.0037888456 [1.0697721] [-0.15860838]
14 0.0036088685 [1.0680948] [-0.15479554]
15 0.0034374492 [1.0664579] [-0.15107438]
16 0.0032741735 [1.0648602] [-0.14744265]
17 0.0031186407 [1.0633011] [-0.1438982]
18 0.0029705027 [1.0617794] [-0.14043899]
19 0.0028293983 [1.0602943] [-0.13706294]
20 0.0026950042 [1.0588448] [-0.13376807]
21 0.0025669914 [1.0574303] [-0.13055237]
22 0.0024450591 [1.0560496] [-0.127414]
23 0.0023289144 [1.0547023] [-0.12435104]
24 0.0022182898 [1.0